name: Node.js CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node_version: [14]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}

            - name: Install dependencies
              run: npm ci

            - name: Run test
              run: PORT=0 npm test

            - name: Trigger deployment
              run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
